version: '2'
services:

  #Maria DB
  # mariadb:
  #  container_name: mariadb
  #  image: mariadb:10.5.9
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=spark
  #    - MYSQL_USER=spark
  #    - MYSQL_PASSWORD=spark
  #    - MYSQL_DATABASE=sparkde
  #  ports:
  #    - '3306:3306'

  mongo:
      ports:
          - '27017:27017'
      container_name: dkrcomp-mongo
      restart: always
      logging:
          options:
              max-size: 1g
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
      image: mongo

  #Zookeeper Service.

  #Zookeeper Service.
  #Image Tag: bitnami/zookeeper:3.6.2

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper

  #Kafka Service
  #Image Tag: bitnami/kafka:2.7.0

  kafka1:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9092:9092'
      - '29092:29092'

    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes

    container_name: kafka-broker1

    depends_on:
      - "zookeeper"


#  Redis
  # redis:
  #  container_name: redis
  #  image: redis:6.2.1-alpine3.13
  #  ports:
  #    - '6379:6379'


  #KafDrop UI for management
  #Image Tag: obsidiandynamics/kafdrop:3.27.0

  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    restart: "no"
    ports:
      - 9000:9000
    
    environment:
      - KAFKA_BROKERCONNECT=kafka1:29092,kafka2:29093,kafka3:29094
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    
    container_name: kafdrop
    depends_on:
      - "kafka1"


